import { Outfit } from "next/font/google";
import "./globals.css";

// Components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Theme provider
import { ThemeProvider } from "@/components/ThemeProvide";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "GabrielDev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ThemeProvider attribute='class' defaultThene='light'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
       
        </body>
    </html>
  );
}
